### ISSUE TITLE
Local Storage RTL Storage Shared Between Apps

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/storybook-addons#1]
#### Describe the bug
When having more than one window open, the current selected RTL/LTR direction is stored between sessions.

#### What is the expected behavior?
This info should not be stored in local storage.

#### What are the steps to reproduce?
Open two windows side-by-side, go to a component and toggle the RTL addon.  

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/88956201-024a9f80-d26b-11ea-8eed-c77e3c0cfb18.png)

**Comment by huayunh** [comment]
Use session storage instead of local storage
